=== taniacristina/Wiki-Familia-Addams/Versão 1/XML/filmes.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT FILMES (FILME)+>
<!ATTLIST FILMES
  xmlns CDATA #FIXED ''>

<!ELEMENT FILME (TITULO,DATA,IMAGEM,LEGENDA,VIDEO,DESCRICAO,RESUMO,
                 PERSONAGENS,LINK)>
<!ATTLIST FILME
  xmlns CDATA #FIXED ''>

<!ELEMENT TITULO (#PCDATA)>
<!ATTLIST TITULO
  xmlns CDATA #FIXED ''>

<!ELEMENT DATA (#PCDATA)>
<!ATTLIST DATA
  xmlns CDATA #FIXED ''>

<!ELEMENT IMAGEM (#PCDATA)>
<!ATTLIST IMAGEM
  xmlns CDATA #FIXED ''>

<!ELEMENT LEGENDA (#PCDATA)>
<!ATTLIST LEGENDA
  xmlns CDATA #FIXED ''>

<!ELEMENT VIDEO (#PCDATA)>
<!ATTLIST VIDEO
  xmlns CDATA #FIXED ''>

<!ELEMENT DESCRICAO (#PCDATA)>
<!ATTLIST DESCRICAO
  xmlns CDATA #FIXED ''>

<!ELEMENT RESUMO (#PCDATA)>
<!ATTLIST RESUMO
  xmlns CDATA #FIXED ''>

<!ELEMENT PERSONAGENS (#PCDATA)>
<!ATTLIST PERSONAGENS
  xmlns CDATA #FIXED ''>

<!ELEMENT LINK (#PCDATA)>
<!ATTLIST LINK
  xmlns CDATA #FIXED ''>

=== taniacristina/Wiki-Familia-Addams/Versão 1/XML/filmes.xml
<!DOCTYPE FILMES SYSTEM "filmes.dtd">
<FILMES     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.cm/xml filmes.xsd">
    <!-- Filme 1 -->
    <FILME>
        <TITULO>Halloween com a nova Família Adams</TITULO>
        <DATA>Lançado em 30 de outubro de 1977</DATA>
        <IMAGEM>IMG/1977.jpg</IMAGEM>
        <LEGENDA>Capa: Halloween com a nova Família Adams</LEGENDA>
        <VIDEO>VIDEO/1977.mp4</VIDEO>
        <DESCRICAO>Trailer: Halloween com a nova Família Adams</DESCRICAO>
        <RESUMO>
            O dia das bruxas está próximo, e Pancho conta às crianças a lenda do personagem de Great Pumpkin,
            de Primo Shy, que distribui presentes e esculpe abóboras para crianças boas na noite de Halloween.
        </RESUMO>
        <PERSONAGENS>
            Morticia Addams, Wandinha Addams, Tio Fester Addams, Primo Coisa, Pugsley Addams, Gomez Addams e Pancho Addams.
        </PERSONAGENS>
        <LINK>https://www.devotudoaocinema.com.br/2018/07/familia-addams-serie.html</LINK>
    </FILME>
    <!-- Filme 2 -->
    <FILME>
        <TITULO>A Família Addams</TITULO>
        <DATA>Lançado em 20 de dezembro de 1991</DATA>
        <IMAGEM>IMG/1991.jpeg</IMAGEM>
        <LEGENDA>Capa: A Família Addams</LEGENDA>
        <VIDEO>VIDEO/1991.mp4</VIDEO>
        <DESCRICAO>Trailer: A Família Addams</DESCRICAO>
        <RESUMO>
            Quando um homem dizendo ser Funério, o irmão desaparecido de Gomez Addams,
            chega à casa dos Addams, a família está feliz. No entanto, Morticia começa 
            a suspeitar que Funério é uma fraude, já que ele não consegue se lembrar de
            detalhes da sua vida. Com a ajuda do advogado Tully Alford, Funério consegue
            fazer com que o clã Addams seja despejado de sua casa. Gomez percebe que os 
            dois homens estão conspirando para roubar a fortuna de sua família.
        </RESUMO>
        <PERSONAGENS>
            Morticia Addams, Wandinha Addams, Tio Fester Addams, Primo Coisa, Gomez Addams e Pancho Addams.
        </PERSONAGENS>
        <LINK>http://www.adorocinema.com/filmes/filme-26230/</LINK>
    </FILME>
    <!-- Filme 3 -->
    <FILME>
        <TITULO>A Família Addams - Retorno</TITULO>
        <DATA>Lançado em 19 de novembro de 1993</DATA>
        <IMAGEM>IMG/1993.jpg</IMAGEM>
        <LEGENDA>Capa: A Família Addams - Retorno</LEGENDA>
        <VIDEO>VIDEO/1993.mp4</VIDEO>
        <DESCRICAO>Trailer: A Família Addams - Retorno</DESCRICAO>
        <RESUMO>
            Os membros da estranha Família Addams fazem mais palhaçadas macabras que antes. 
            Desta vez, Gomez Addams e sua esposa Mortícia estão comemorando a chegada de um bebê.
            Porém os irmãos Wednesday e Pugsley não estão muito felizes com a novidade e tentam eliminar o bebê.
            Quando a babá Debbie Jelinsky aparece para manter as crianças na linha, sua presença leva a uma 
            revira-volta inesperada.
        </RESUMO>
        <PERSONAGENS>
            Morticia Addams, Wandinha Addams, Tio Fester Addams, Primo Coisa, Gomez Addams e Pancho Addams.
        </PERSONAGENS>
        <LINK>http://www.adorocinema.com/filmes/filme-9023/</LINK>
    </FILME>
    <!-- Filme 4 -->
    <FILME>
        <TITULO>A Família Addams - Reunião</TITULO>
        <DATA>Lançado em 22 de setembro de 1998</DATA>
        <IMAGEM>IMG/1998.jpeg</IMAGEM>
        <LEGENDA>Capa: A Família Addams - Reunião</LEGENDA>
        <VIDEO>VIDEO/1998.mp4</VIDEO>
        <DESCRICAO>Trailer: A Família Addams - Reunião</DESCRICAO>
        <RESUMO>
            Gomez e Morticia preparam tudo para as férias, quando são surpreendidos por outro convite:
            uma reunião familiar. Só que ao chegar, eles descobrem que a reunião não é da família A-D-D-A-M-S,
            e sim da família A-D-A-M-S, completamente diferente da sua.  
        </RESUMO>
        <PERSONAGENS>
            Morticia Addams, Wandinha Addams, Tio Fester Addams, Primo Coisa, Gomez Addams e Pancho Addams.
        </PERSONAGENS>
        <LINK>https://filmow.com/o-retorno-da-familia-addams-t10660/</LINK>
    </FILME>
    <!-- Filme 5 -->
    <FILME>
        <TITULO>A Família Addams</TITULO>
        <DATA>Lançado em 24 de outubro de 2019</DATA>
        <IMAGEM>IMG/2019.jpg</IMAGEM>
        <LEGENDA>Capa: A Família Addams</LEGENDA>
        <VIDEO>VIDEO/2019.mp4</VIDEO>
        <DESCRICAO>Trailer: A Família Addams</DESCRICAO>
        <RESUMO>
            A vida da família Addams começa a se desenrolar quando eles precisam enfrentar
            uma apresentadora de televisão traiçoeira, gananciosa, arrogante e astuta. 
            Ao mesmo tempo, os Addams se preparam para receber os outros membros de sua família
            para uma grande festa.  
        </RESUMO>
        <PERSONAGENS>
            Morticia Addams, Wandinha Addams, Tio Fester Addams, Primo Coisa, Gomez Addams e Pancho Addams.
        </PERSONAGENS>
        <LINK>http://www.adorocinema.com/filmes/filme-26230/fotos/</LINK>
    </FILME>
</FILMES>
